from django.conf.urls.defaults import *
from views import *

urlpatterns = patterns('',
    (r'^arrivals/add/$', add_arrival),
    (r'^arrivals/edit/(?P<arrival_id>\d+)/$', edit_arrival),
    (r'^arrivals/delete/(?P<arrival_id>\d+)/$', delete_arrival),
    (r'^arrivals/$', list_arrivals),
    (r'^confirm/(?P<match_id>\d+)/$', confirm_match),
    (r'^cancel/(?P<match_id>\d+)/$', cancel_match),    
    (r'^deny/(?P<match_id>\d+)/$', deny_match),
    (r'^matches/$', info_matches),
    (r'^ride/matches/(?P<match_id>\d+)/map/$', show_match_map),
    (r'^ride/matches/(?P<match_id>\d+)/$', show_match),
    (r'^ride/matches/$', list_ride_matches),
    (r'^ride/edit/(?P<ride_id>\d+)/$', edit_ride),
    (r'^ride/delete/(?P<ride_id>\d+)/$', delete_ride),
    (r'^ride/add/$', add_ride),
    (r'^ride/archives$', list_old_ride),
    (r'^ride/(?P<ride_id>\d+)/$', show_ride),
    (r'^ride/$', list_ride),
    (r'^rides/$', info_rides),
    (r'^passenger/edit/(?P<passenger_id>\d+)/$', edit_passenger),
    (r'^passenger/delete/(?P<passenger_id>\d+)/$', delete_passenger),
    (r'^passenger/search/(?P<passenger_id>\d+)/$', search),
    (r'^passenger/add/$', add_passenger),
    (r'^passenger/archives/$', list_old_passenger),
    (r'^passenger/matches/$', list_passenger_matches),
    (r'^passenger/(?P<passenger_id>\d+)/$', show_passenger),
    (r'^passenger/$', list_passenger),
)